### ISSUE TITLE
Double quotes are not handled properly when in args with spaces

### ISSUE THREAD

**Issue by ransombriggs** [heroku/heroku-run#12]
@dickeyxxx When I was reviewing https://github.com/heroku/heroku-run/pull/9 I noticed a bug in the buildCommand method here https://github.com/heroku/heroku-run/blob/88a7cc3f9efd1ec5fc3906a60d57d50bd6608c73/lib/run.js#L15 .   If someone passes in an arg with spaces and double quotes, the quotes no longer balance when passed in.

```
-> % heroku run echo 'foo " bar'
--> POST /apps/app/dynos
--> {"command":"echo \"foo \" bar\"","attach":true,"env":{"TERM":"xterm-256color","COLUMNS":157,"LINES":81}}
Running echo "foo " bar" on app... <-- 201 Created
<-- 
up, run.2196
bash: -c: line 0: unexpected EOF while looking for matching `"'
bash: -c: line 1: syntax error: unexpected end of file
```

**Comment by dickeyxxx** [comment]
did you see https://github.com/heroku/heroku-run/pull/10?

**Comment by ransombriggs** [comment]
Closing as duplicate.
