### ISSUE TITLE
undefined in run:inside output

### ISSUE THREAD

**Issue by ransombriggs** [heroku/heroku-run#22]
```
Running bash on ⬢ foo-bar ... up, web.1 (undefined)
```
The problem is that we use `dyno.size` but it is not defined for the run inside endpoint that we hit, we either need to add to the serializer in API or pull in the CLI.

**Comment by dickeyxxx** [comment]
can we just hide the output if it's undefined?

**Comment by ransombriggs** [comment]
@dickeyxxx that would also be an acceptable solution since this is for an existing dyno it is not as helpful to know its size, since you cannot configure it anyways

**Comment by dickeyxxx** [comment]
#22
