### ISSUE TITLE
If `heroku run` isn't passed a command, it reads a flag as the command

### ISSUE THREAD

**Issue by daneharrigan** [heroku/heroku-run#28]
Originally reported here: heroku/dogwood#635

`heroku run --example -a $APP` will send `--example` as the command to be run.

**Comment by dickeyxxx** [comment]
cc @uhoh-itsmaciek. I'm not sure what the correct behavior should be here. It sounds like you'd like for the CLI to validate the input? I suppose a bash command could never start with a hyphen, but would it be good for the CLI to start rejecting input like that?

**Comment by uhoh-itsmaciek** [comment]
I don't think this is a CLI issue. I don't know the internals of `heroku run`, but I was expecting output like what happens in my terminal:

```
maciek@mothra:~$ --version
--version: command not found
```

I'm assuming the command is passed to some wrapper command in the dyno, so I was expecting that command to use something like `--` to differentiate between options passed to the wrapper command and the nested command to run. E.g., let's assume the wrapper command is GNU time, and compare the output of the two invocations below:

```
maciek@mothra:~$ cmd="--version"
maciek@mothra:~$ /usr/bin/time $cmd
GNU time 1.7
maciek@mothra:~$ /usr/bin/time -- $cmd
/usr/bin/time: cannot run --version: No such file or directory
Command exited with non-zero status 127
0.00user 0.00system 0:00.00elapsed ?%CPU (0avgtext+0avgdata 1232maxresident)k
0inputs+0outputs (0major+28minor)pagefaults 0swaps
```

I was expecting the second; I got something like the first.

**Comment by amerine** [comment]
> Just painting the whole picture for what happens in both the common and private runtimes:

In both the [common](https://github.com/heroku/railgun/blob/16457c183777300923bd768fbae6adbd6e13b88f/ps-runner/src/ps_runner.cpp#L186) and [private runtimes](https://github.com/heroku/dogwood/blob/master/runtimed/profile/runner.go#L34), the command sent in for a formation/managed Dyno *AND* one-off Dynos is inserted into a `bash -c` call.

**Comment by uhoh-itsmaciek** [comment]
I'm going to close this; it's probably not worth fixing and it is definitely not a CLI issue.
