### ISSUE TITLE
Only print `up` when the rendezvous session has been estabilished

### ISSUE THREAD

**Issue by fabiokung** [heroku/heroku-run#7]
... with attached dynos, [here](https://github.com/heroku/heroku-run/blob/ff0d22d452746ec16051498a50e1c09cb3c21b29/commands/run.js#L126).

IIRC the original CLI command used to do that, and only print `up <dyno.name>` after the rendezvous dance is done, which means the dyno is really running.

**Comment by sclasen** [comment]
:+1:

**Comment by fabiokung** [comment]
If I understand the patch correctly, we don't seem to be quite there yet. The rendezvous session is only estabilished after the handshake is done (the first line from the connection is read, which should contain `"rendezvous "`).

This is what I recall the old client doing:

1. print `Starting command ...`
2. API call, get rendezvous_url back
3. connect to rendezvous_url
4. print `Awaiting ...`
5. read the first `" rendezvous"` line (handshake)
6. print `up`

On Private Spaces, step number 5 can take 2-3min (the dyno instance is booting), which is why it is important that we only print `up` after the rendezvous dance is complete.

**Comment by dickeyxxx** [comment]
@fabiokung sorry this took so long to get in. Does #13 seem more like what it should do? I tested it on a dogwood app, so I think it's correct now.

**Comment by fabiokung** [comment]
no worries! Yes, #13 sgtm.
